spring:

    profiles:
        
active:
        - dev

---
server:

    port: 8001
spring:

    profiles: dev
    application:

        name : microservicecloud-config-dept-client
    datasource:
            
type: com.alibaba.druid.pool.DruidDataSource
            driver-class-name: com.mysql.cj.jdbc.Driver
            url:  jdbc : mysql:// localhost: 3306/test?serverTimezone=UTC
            username : root
            
password: hahaha
            dbcp2:

                min-idle: 5
                
initial-size: 5
                max-total: 5

                max-wait-mi1lis: 200

mybatis:
    
config-location: classpath: mybatis/mybatis.cfg. xml

    type-aliases-package: com.xy.springcloud.entities
    mapper-locations:

    - classpath : mybatis/mapper/**/*.xml

eureka:
    
client:
        service-url:

            defaultZone: http: //eureka7001.com:7001/eureka

info:
    app.name: springcloud01
    company-name: www.xy.com
    build.artifactId: $project.artifactId$
    bulid.version: $projet.version$